export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_TRANSACTIONS_BEGIN = 'GET_TRANSACTIONS_BEGIN'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const CREATE_TRANSACTION_BEGIN = 'CREATE_TRANSACTION_BEGIN'
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const DELETE_TRANSACTION_BEGIN = 'DELETE_TRANSACTION_BEGIN'
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS'

export const GET_SAVINGS_BEGIN = 'GET_SAVINGS_BEGIN'
export const GET_SAVINGS_SUCCESS = 'GET_SAVINGS_SUCCESS'
export const CREATE_SAVING_BEGIN = 'CREATE_SAVING_BEGIN'
export const CREATE_SAVING_SUCCESS = 'CREATE_SAVING_SUCCESS'
export const DELETE_SAVING_BEGIN = 'DELETE_SAVING_BEGIN'
export const DELETE_SAVING_SUCCESS = 'DELETE_SAVING_SUCCESS'
export const UPDATE_SAVING_BEGIN = 'UPDATE_SAVING_BEGIN'
export const UPDATE_SAVING_SUCCESS = 'UPDATE_SAVING_SUCCESS'
